### PR TITLE
Update TensorStore

### PR DESCRIPTION
**Pull request by dzenanz**
Update is accomplished by rebasing and adding a minor compile fix.

### CODE REVIEW

**Review by tbirdso — APPROVED** [review]
Nice! Rebase looks good, two questions/requests:
1. Can we confirm that zip functionality is still working after the rebase? Covered under unit testing?
2. Do we have a way to revert if something has gone wrong in the rebase? Maybe a copy of the old `master` branch is or could be maintained?

**Comment by dzenanz** [comment]
1. All the tests are passing on Windows, reliably. Some tests are still flaky on Linux.
1. Yes, we could create a new branch for each new release, and have the master coincide with our latest custom release.

**Comment by dzenanz** [comment]
I created branches here, called `release1-2868eab` and `release2-e371f6e`. After we [check whether the bug fixes work with release1](https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/actions/runs/5826016232/job/16417773891?pr=44), we can repoint master to release2.

**Comment by dzenanz** [comment]
I now realize that previous link is not the best check of release1 working, but https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/pull/54. This [run](https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/actions/runs/5826016232/job/16417773891?pr=44) and corresponding [dashboard build](https://open.cdash.org/build/8957426) just tell us that the bug fix did not introduce any new problems for the old code.

**Comment by dzenanz** [comment]
We should probably have a tagged and released package with the old version before we pull the trigger on this. To be done after https://github.com/InsightSoftwareConsortium/ITKIOOMEZarrNGFF/pull/44.

**Comment by dzenanz** [comment]
Skipping this intermediate version. I repointed master to 9d45c2f3aa13618d215d3370ef09d089986215c7.

**Pull request merged**
